### PR TITLE
updates for Meteor 3

### PR DESCRIPTION
**Pull request by copleykj**
Not sure if these changes are complete. I tried to run the tests but getting strange errors and I couldn't find any info on running the tests. That being said, these changes seem to work within my local project so they're at least a start.

### CODE REVIEW

**Comment by timsun28** [comment]
Hi,

Thank you for creating this pull request!
I was able to run the tests locally after running ```meteor npm i``` and afterwards ```meteor test-packages ./``` in the project folder and viewing the results on localhost:3000. It seems like all the tests are passing. 

There is also a [discussion](https://github.com/zodern/meteor-relay/issues/13) going on here about the Meteor 3.0 support, where this can be discussed in further details. 

Finally, it will be @zodern who will be able to verify and merge the code so this package can be used properly with Meteor 3.0.

**Comment by copleykj** [comment]
@timsun28 Awesome. Thanks for verifying the tests are working. I'll eagerly await Zodern's review

**Comment by timsun28** [comment]
I've tested your version for meteor 3 in a small demo project for Tanstack query with meteor 3.0 and got everything to work except a minor issue where meteor was complaining that there was a typescript mismatch. I got this resolved by changing line 14 of package.js to this: ```api.versionsFrom(["2.2", "3.0"]);``` This for some reason allowed it to install this version of typescript that was required. If you could add that to your version as well than we can use my demo app to test your pr as well.

**Comment by welkinwong** [comment]
@copleykj  I don't how to submit pr from your pr.
use pipeline with meteor3 need change  `pipeline-helpers.ts`

key is `cursor.observe` to `cursor.observeAsync` and `cursor.observeChanges` to `cursor.observeChangesAsync`

**line 44:**
```ts
export function withCursors<I extends object, T extends Record<string, Mongo.Cursor<any>>>(input: I, cursors: T):
  I & { [K in keyof T]: T[K] extends Mongo.Cursor<infer X> ? X[] : never } {
```
to
```ts
export async function withCursors<I extends object, T extends Record<string, Mongo.Cursor<any>>>(input: I, cursors: T): 
Promise<I & { [K in keyof T]: T[K] extends Mongo.Cursor<infer X> ? X[] : never }> {
```

---

**line 49:**
```ts
  let docs: {
    [K in keyof T]: T[K] extends Mongo.Cursor<infer X> ? X[] : never
  } = Object.entries(cursors).reduce((result: any, [name, cursor]) => {
```
to
```ts
  let docs: {
    [K in keyof T]: T[K] extends Mongo.Cursor<infer X> ? X[] : never;
  } = await Object.entries(cursors).reduce(async (result: any, [name, cursor]) => {
```

---

**line 55:**
```ts
let handle = cursor.observe({
```
to
```ts
let handle = await cursor.observeAsync({
```

---

**line 133:**
```ts
    cursors.forEach(cursor => {
```
to
```ts
    cursors.forEach(async cursor => {
```

---

**line 140:**
```ts
      let handle = cursor.observeChanges({
```
to
```ts
      let handle = await cursor.observeChangesAsync({
```

**Comment by zodern** [comment]
Thanks for working on this @copleykj. I did it a little differently in `zodern:relay@2.0.0-beta.1` so we can keep support for Meteor 2.

**Comment by copleykj** [comment]
Awesome. Thanks @zodern

**Pull request closed without merging**
